"""Ajout image_url à Formule

Revision ID: c265c19004fd
Revises: 
Create Date: 2025-07-13 18:41:57.462181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c265c19004fd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('donneespoteau', 'Ath_cent')
    op.drop_column('donneespoutre', 'c')
    op.drop_column('donneespoutrelle', 'pu')
    op.drop_column('donneespoutrelle', 'ps')
    op.add_column('formule', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('formule', 'image_url')
    op.add_column('donneespoutrelle', sa.Column('ps', sa.FLOAT(), nullable=True))
    op.add_column('donneespoutrelle', sa.Column('pu', sa.FLOAT(), nullable=True))
    op.add_column('donneespoutre', sa.Column('c', sa.FLOAT(), nullable=True))
    op.add_column('donneespoteau', sa.Column('Ath_cent', sa.FLOAT(), nullable=True))
    # ### end Alembic commands ###
